name: loop
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - openai
    - gradio
    - ddgs
    - playwright==1.41.2
    - rich
    - typer
    - docker
    - kubernetes
    - .
